Script started on Thu 26 Oct 2017 01:28:15 AM PDT
]0;andersvn@bondi:~/hw2[andersvn@bondi ~/hw2]$ ./PhotoLab[25G[37@gcc PhotoLab.c -ansi -std=c99 -Wall -o [72G
]0;andersvn@bondi:~/hw2[andersvn@bondi ~/hw2]$ gcc PhotoLab.c -ansi -std=c99 -Wall -o PhotoLab[25G[37P./[35G
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black and White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 11
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
Black and White tested!

HSSOE.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

HSSOE.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
Edge tested!

HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle tested!

HSSOE.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
VFlip tested!

HSSOE.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
VMirror tested!

HSSOE.ppm was read.
border.ppm was saved. 
border.jpg was stored.
AddBorder tested!

1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black and White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 12
]0;andersvn@bondi:~/hw2[andersvn@bondi ~/hw2]$ exit
exit

Script done on Thu 26 Oct 2017 01:28:51 AM PDT
