Script started on Wed 08 Nov 2017 04:34:31 AM PST
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ make clean
rm -rf *o PhotoLab 
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ make 
gcc -Wall -ansi -std=c99 -c FileIO.c -o FileIO.o
gcc -Wall -ansi -std=c99 -c Advanced.c -o Advanced.o 
gcc -Wall -ansi -std=c99 -c DIPs.c -o DIPs.o
cc    -c -o PhotoLab.o PhotoLab.c
gcc -Wall -ansi -std=c99 FileIO.o Advanced.o DIPs.o PhotoLab.o -o PhotoLab
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen the image
13: Posterize the image
14: Blur the image
15: Test all functions
16: Exit
Please make your choice: 15
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
Black & White tested!

HSSOE.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

HSSOE.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
Edge Detection tested!

HSSOE.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
VMirror tested!

HSSOE.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
VFlip tested!

HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle tested!

HSSOE.ppm was read.
border.ppm was saved. 
border.jpg was stored.
Border tested!

HSSOE.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
Noise tested!

HSSOE.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
Sharpen tested!

HSSOE.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
Posterize tested!

HSSOE.ppm was read.
motion_blur.ppm was saved. 
motion_blur.jpg was stored.
MotionBlur tested!


----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen the image
13: Posterize the image
14: Blur the image
15: Test all functions
16: Exit
Please make your choice: 16
You exit the program.
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ make PhotoLabTest
gcc -Wall -ansi -std=c99 -c PhotoLab.c -o PhotoLabTest
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ touch Advanced.c
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ make PhotoLab
gcc -Wall -ansi -std=c99 -c Advanced.c -o Advanced.o 
gcc -Wall -ansi -std=c99 FileIO.o Advanced.o DIPs.o PhotoLab.o -o PhotoLab
]0;andersvn@bondi:~/hw3[andersvn@bondi ~/hw3]$ exit
exit

Script done on Wed 08 Nov 2017 04:36:02 AM PST
